In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df=pd.read_csv('/content/ONGC.csv')
df

Date Symbol Series  Prev Close    Open   High     Low    Last  \
0     2000-01-03   ONGC     EQ      207.70  205.00  214.4  205.00  214.00   
1     2000-01-04   ONGC     EQ      213.45  201.50  209.7  201.00  209.00   
2     2000-01-05   ONGC     EQ      206.55  201.00  223.1  200.50  223.10   
3     2000-01-06   ONGC     EQ      223.10  234.00  234.9  217.60  217.60   
4     2000-01-07   ONGC     EQ      219.30  223.00  223.0  213.00  215.70   
...          ...    ...    ...         ...     ...    ...     ...     ...   
5301  2021-04-26   ONGC     EQ      102.40  105.25  105.7  102.50  102.80   
5302  2021-04-27   ONGC     EQ      102.80  102.80  104.0  102.80  103.30   
5303  2021-04-28   ONGC     EQ      103.20  103.75  104.4  103.30  104.05   
5304  2021-04-29   ONGC     EQ      103.90  104.90  105.9  103.55  104.30   
5305  2021-04-30   ONGC     EQ      104.05  104.15  112.7  103.30  108.20   

       Close    VWAP    Volume      Turnover    Trades  Deliverable Volume  \
0     213.45  209.91      9600  2.015090e+11       NaN                 NaN   
1     206.55  206.26     17900  3.692030e+11       NaN                 NaN   
2     223.10  215.46     27000  5.817490e+11       NaN                 NaN   
3     219.30  223.42     35600  7.953680e+11       NaN                 NaN   
4     215.75  215.19     11400  2.453145e+11       NaN                 NaN   
...      ...     ...       ...           ...       ...                 ...   
5301  102.80  103.86  11797791  1.225355e+14   63132.0           3024740.0   
5302  103.20  103.42   8886250  9.189768e+13   46923.0           3802836.0   
5303  103.90  103.90   6887787  7.156081e+13   33659.0           2533669.0   
5304  104.05  104.39  14990087  1.564876e+14   54416.0           4613745.0   
5305  108.15  109.79  81358264  8.932632e+14  248419.0          15306987.0   

      %Deliverble  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             NaN  
...           ...  
5301       0.2564  
5302       0.4279  
5303       0.3678  
5304       0.3078  
5305       0.1881  

[5306 rows x 15 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5306 entries, 0 to 5305
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Date                5306 non-null   object 
 1   Symbol              5306 non-null   object 
 2   Series              5306 non-null   object 
 3   Prev Close          5306 non-null   float64
 4   Open                5306 non-null   float64
 5   High                5306 non-null   float64
 6   Low                 5306 non-null   float64
 7   Last                5306 non-null   float64
 8   Close               5306 non-null   float64
 9   VWAP                5306 non-null   float64
 10  Volume              5306 non-null   int64  
 11  Turnover            5306 non-null   float64
 12  Trades              2456 non-null   float64
 13  Deliverable Volume  4797 non-null   float64
 14  %Deliverble         4797 non-null   float64
dtypes: float64(11), int64(1), object(3)
memory usage: 621.9

In [ ]:
d=df.drop(['Date','Symbol','Series'], axis=1)
d

Prev Close    Open   High     Low    Last   Close    VWAP    Volume  \
0         207.70  205.00  214.4  205.00  214.00  213.45  209.91      9600   
1         213.45  201.50  209.7  201.00  209.00  206.55  206.26     17900   
2         206.55  201.00  223.1  200.50  223.10  223.10  215.46     27000   
3         223.10  234.00  234.9  217.60  217.60  219.30  223.42     35600   
4         219.30  223.00  223.0  213.00  215.70  215.75  215.19     11400   
...          ...     ...    ...     ...     ...     ...     ...       ...   
5301      102.40  105.25  105.7  102.50  102.80  102.80  103.86  11797791   
5302      102.80  102.80  104.0  102.80  103.30  103.20  103.42   8886250   
5303      103.20  103.75  104.4  103.30  104.05  103.90  103.90   6887787   
5304      103.90  104.90  105.9  103.55  104.30  104.05  104.39  14990087   
5305      104.05  104.15  112.7  103.30  108.20  108.15  109.79  81358264   

          Turnover    Trades  Deliverable Volume  %Deliverble  
0     2.015090e+11       NaN                 NaN          NaN  
1     3.692030e+11       NaN                 NaN          NaN  
2     5.817490e+11       NaN                 NaN          NaN  
3     7.953680e+11       NaN                 NaN          NaN  
4     2.453145e+11       NaN                 NaN          NaN  
...            ...       ...                 ...          ...  
5301  1.225355e+14   63132.0           3024740.0       0.2564  
5302  9.189768e+13   46923.0           3802836.0       0.4279  
5303  7.156081e+13   33659.0           2533669.0       0.3678  
5304  1.564876e+14   54416.0           4613745.0       0.3078  
5305  8.932632e+14  248419.0          15306987.0       0.1881  

[5306 rows x 12 columns]

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5306 entries, 0 to 5305
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Prev Close          5306 non-null   float64
 1   Open                5306 non-null   float64
 2   High                5306 non-null   float64
 3   Low                 5306 non-null   float64
 4   Last                5306 non-null   float64
 5   Close               5306 non-null   float64
 6   VWAP                5306 non-null   float64
 7   Volume              5306 non-null   int64  
 8   Turnover            5306 non-null   float64
 9   Trades              2456 non-null   float64
 10  Deliverable Volume  4797 non-null   float64
 11  %Deliverble         4797 non-null   float64
dtypes: float64(11), int64(1)
memory usage: 497.6 KB


In [ ]:
d.dropna(inplace=True)
d

Prev Close    Open    High     Low    Last   Close    VWAP    Volume  \
2850      281.05  283.00  284.30  278.20  282.00  281.60  281.78   1969133   
2851      281.60  279.50  285.60  278.35  280.65  281.10  282.57   2716496   
2852      281.10  281.25  283.90  278.60  280.10  280.00  280.92   1623442   
2853      280.00  278.10  279.75  275.30  275.70  275.85  276.50   1436297   
2854      275.85  275.00  277.50  273.00  277.45  276.35  275.49   3045575   
...          ...     ...     ...     ...     ...     ...     ...       ...   
5301      102.40  105.25  105.70  102.50  102.80  102.80  103.86  11797791   
5302      102.80  102.80  104.00  102.80  103.30  103.20  103.42   8886250   
5303      103.20  103.75  104.40  103.30  104.05  103.90  103.90   6887787   
5304      103.90  104.90  105.90  103.55  104.30  104.05  104.39  14990087   
5305      104.05  104.15  112.70  103.30  108.20  108.15  109.79  81358264   

          Turnover    Trades  Deliverable Volume  %Deliverble  
2850  5.548532e+13   35221.0            858592.0       0.4360  
2851  7.676109e+13   44234.0           1141200.0       0.4201  
2852  4.560549e+13   22410.0            771670.0       0.4753  
2853  3.971384e+13   27811.0            761602.0       0.5303  
2854  8.390230e+13   40454.0           1636427.0       0.5373  
...            ...       ...                 ...          ...  
5301  1.225355e+14   63132.0           3024740.0       0.2564  
5302  9.189768e+13   46923.0           3802836.0       0.4279  
5303  7.156081e+13   33659.0           2533669.0       0.3678  
5304  1.564876e+14   54416.0           4613745.0       0.3078  
5305  8.932632e+14  248419.0          15306987.0       0.1881  

[2456 rows x 12 columns]

In [ ]:
d.corr()

Prev Close      Open      High       Low      Last  \
Prev Close            1.000000  0.999391  0.998834  0.998789  0.998250   
Open                  0.999391  1.000000  0.999365  0.999268  0.998677   
High                  0.998834  0.999365  1.000000  0.999156  0.999437   
Low                   0.998789  0.999268  0.999156  1.000000  0.999359   
Last                  0.998250  0.998677  0.999437  0.999359  1.000000   
Close                 0.998265  0.998708  0.999481  0.999385  0.999965   
VWAP                  0.998817  0.999307  0.999755  0.999674  0.999747   
Volume               -0.495996 -0.495123 -0.486588 -0.499218 -0.493092   
Turnover             -0.131481 -0.128663 -0.116993 -0.135003 -0.125621   
Trades               -0.156357 -0.154275 -0.142449 -0.162170 -0.152247   
Deliverable Volume   -0.400079 -0.399816 -0.392370 -0.403981 -0.398491   
%Deliverble           0.491799  0.490269  0.485529  0.493744  0.488908   

                       Close      VWAP    Volume  Turnover    Trades  \
Prev Close          0.998265  0.998817 -0.495996 -0.131481 -0.156357   
Open                0.998708  0.999307 -0.495123 -0.128663 -0.154275   
High                0.999481  0.999755 -0.486588 -0.116993 -0.142449   
Low                 0.999385  0.999674 -0.499218 -0.135003 -0.162170   
Last                0.999965  0.999747 -0.493092 -0.125621 -0.152247   
Close               1.000000  0.999791 -0.492788 -0.125349 -0.151943   
VWAP                0.999791  1.000000 -0.493022 -0.125873 -0.152275   
Volume             -0.492788 -0.493022  1.000000  0.828680  0.745926   
Turnover           -0.125349 -0.125873  0.828680  1.000000  0.812309   
Trades             -0.151943 -0.152275  0.745926  0.812309  1.000000   
Deliverable Volume -0.398156 -0.398545  0.885889  0.824614  0.636332   
%Deliverble         0.488899  0.488909 -0.414312 -0.201509 -0.270596   

                    Deliverable Volume  %Deliverble  
Prev Close                   -0.400079     0.491799  
Open                         -0.399816     0.490269  
High                         -0.392370     0.485529  
Low                          -0.403981     0.493744  
Last                         -0.398491     0.488908  
Close                        -0.398156     0.488899  
VWAP                         -0.398545     0.488909  
Volume                        0.885889    -0.414312  
Turnover                      0.824614    -0.201509  
Trades                        0.636332    -0.270596  
Deliverable Volume            1.000000    -0.133976  
%Deliverble                  -0.133976     1.000000

# Simple Linear Regressor

In [ ]:
X= d.iloc[:, 5:6].values
X

array([[281.6 ],
       [281.1 ],
       [280.  ],
       ...,
       [103.9 ],
       [104.05],
       [108.15]])

In [ ]:
y= d.iloc[:, 6].values
y

array([281.78, 282.57, 280.92, ..., 103.9 , 104.39, 109.79])

# Splitting Dataset into Training & Testing set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

# Training Simple Linear Model on Training Set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

# Predicting the Test set result

In [ ]:
y_pred=regressor.predict(X_test)
y_pred

array([207.9024, 276.5084,  78.141 , 343.2143, 216.2531, 148.7472,
       158.9981, 317.162 , 298.2103, 128.0954, 162.6984, 196.1514,
       256.4067, 343.1643, 250.8562, 264.8074, 169.399 ,  69.2902,
       166.0487, 179.2499, 251.6062, 247.2559, 104.7933, 268.1577,
       219.6034, 305.411 , 218.3533, 257.8068, 288.4595, 158.098 ,
       289.0595, 128.2454, 315.2118, 261.9072, 265.4075, 117.0944,
       279.1087, 277.1085, 102.9932, 304.9109, 161.8484, 158.148 ,
       329.4631, 169.599 , 274.6583, 229.5043, 320.4623, 326.9129,
       180.3   , 283.9591, 408.7201, 137.5962, 385.918 ,  67.7901,
       166.2988, 278.8086,  79.1911, 257.4568, 305.1109, 141.8466,
       392.9187, 321.9624, 328.063 , 102.1931, 160.1982, 273.5582,
        71.7904, 126.6453, 166.5488, 333.3134, 199.7017,  77.841 ,
       165.3487, 317.412 , 143.6468, 180.85  ,  67.7401, 261.2571,
       171.5992, 274.1082, 122.8949, 313.5617, 171.6992, 280.7088,
       225.2539, 261.3071, 177.5497, 128.0454, 270.1579, 306.5

In [ ]:
y_test

array([207.88, 276.28,  77.92, 341.3 , 215.7 , 148.88, 160.29, 320.6 ,
       298.25, 126.57, 161.72, 195.91, 257.41, 339.68, 248.89, 267.03,
       168.4 ,  69.86, 165.73, 180.57, 252.03, 246.86, 104.58, 267.28,
       220.72, 300.02, 220.34, 256.78, 280.47, 158.29, 288.06, 128.71,
       316.18, 264.53, 265.35, 118.71, 279.25, 277.21, 103.56, 304.28,
       160.86, 158.62, 328.51, 169.55, 276.94, 226.64, 317.26, 326.77,
       180.24, 282.49, 410.04, 137.94, 385.84,  68.19, 165.07, 276.05,
        79.29, 258.67, 306.62, 140.43, 390.26, 324.84, 329.88, 101.63,
       159.97, 277.83,  71.48, 126.59, 167.53, 338.43, 200.11,  78.6 ,
       166.53, 314.28, 142.76, 180.94,  68.44, 262.62, 172.24, 274.82,
       123.33, 313.23, 170.95, 282.86, 225.43, 261.16, 178.1 , 127.63,
       271.81, 308.59, 289.64, 154.82,  76.75, 131.28, 406.39, 194.5 ,
       176.88, 185.4 , 290.84, 199.92, 278.36, 119.79, 325.93, 168.37,
       170.62, 283.63, 173.06, 130.41, 188.88,  87.17, 325.49,  63.22,
      

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.9995126613336639


# Multiple Linear Regression

In [ ]:
X= d.iloc[ : , 0:6].values
X

array([[281.05, 283.  , 284.3 , 278.2 , 282.  , 281.6 ],
       [281.6 , 279.5 , 285.6 , 278.35, 280.65, 281.1 ],
       [281.1 , 281.25, 283.9 , 278.6 , 280.1 , 280.  ],
       ...,
       [103.2 , 103.75, 104.4 , 103.3 , 104.05, 103.9 ],
       [103.9 , 104.9 , 105.9 , 103.55, 104.3 , 104.05],
       [104.05, 104.15, 112.7 , 103.3 , 108.2 , 108.15]])

In [ ]:
y= d.iloc[ : , 6].values
y

array([281.78, 282.57, 280.92, ..., 103.9 , 104.39, 109.79])

# Splitting Dataset into Training & Testing set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

# Training Simple Linear Model on Training Set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

# Predicting the Test set result

In [ ]:
y_pred=regressor.predict(X_test)
np.set_printoptions(precision=4) #decimal number 4 tk when(precision=4)
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

array([[207.9924, 207.88  ],
       [275.9612, 276.28  ],
       [ 77.6031,  77.92  ],
       [341.3574, 341.3   ],
       [215.3785, 215.7   ],
       [148.9221, 148.88  ],
       [159.7237, 160.29  ],
       [321.0244, 320.6   ],
       [298.9285, 298.25  ],
       [127.1063, 126.57  ],
       [161.5853, 161.72  ],
       [196.078 , 195.91  ],
       [257.6757, 257.41  ],
       [339.857 , 339.68  ],
       [249.0101, 248.89  ],
       [266.0738, 267.03  ],
       [168.5458, 168.4   ],
       [ 70.3174,  69.86  ],
       [165.997 , 165.73  ],
       [180.3196, 180.57  ],
       [251.9528, 252.03  ],
       [247.3391, 246.86  ],
       [104.4697, 104.58  ],
       [267.0608, 267.28  ],
       [220.7938, 220.72  ],
       [300.6993, 300.02  ],
       [219.3368, 220.34  ],
       [256.9175, 256.78  ],
       [283.8651, 280.47  ],
       [158.315 , 158.29  ],
       [287.7587, 288.06  ],
       [129.0182, 128.71  ],
       [318.4009, 316.18  ],
       [264.2692, 264.53  ],
       [265.46

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.999930771167945


# Polynomial Regressor

In [ ]:
X= d.iloc[ : , 0:6].values
X

array([[281.05, 283.  , 284.3 , 278.2 , 282.  , 281.6 ],
       [281.6 , 279.5 , 285.6 , 278.35, 280.65, 281.1 ],
       [281.1 , 281.25, 283.9 , 278.6 , 280.1 , 280.  ],
       ...,
       [103.2 , 103.75, 104.4 , 103.3 , 104.05, 103.9 ],
       [103.9 , 104.9 , 105.9 , 103.55, 104.3 , 104.05],
       [104.05, 104.15, 112.7 , 103.3 , 108.2 , 108.15]])

In [ ]:
y= d.iloc[ : , 6].values
y

array([281.78, 282.57, 280.92, ..., 103.9 , 104.39, 109.79])

# Training Linear Regression Model

In [ ]:
from sklearn.linear_model import LinearRegression
lin_reg= LinearRegression()
lin_reg.fit(X,y)

LinearRegression()

# Training Polynomial Regression Model

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg= PolynomialFeatures(degree=1)
X_poly= poly_reg.fit_transform(X)

In [ ]:
X

array([[281.05, 283.  , 284.3 , 278.2 , 282.  , 281.6 ],
       [281.6 , 279.5 , 285.6 , 278.35, 280.65, 281.1 ],
       [281.1 , 281.25, 283.9 , 278.6 , 280.1 , 280.  ],
       ...,
       [103.2 , 103.75, 104.4 , 103.3 , 104.05, 103.9 ],
       [103.9 , 104.9 , 105.9 , 103.55, 104.3 , 104.05],
       [104.05, 104.15, 112.7 , 103.3 , 108.2 , 108.15]])

In [ ]:
X_poly

array([[  1.  , 281.05, 283.  , ..., 278.2 , 282.  , 281.6 ],
       [  1.  , 281.6 , 279.5 , ..., 278.35, 280.65, 281.1 ],
       [  1.  , 281.1 , 281.25, ..., 278.6 , 280.1 , 280.  ],
       ...,
       [  1.  , 103.2 , 103.75, ..., 103.3 , 104.05, 103.9 ],
       [  1.  , 103.9 , 104.9 , ..., 103.55, 104.3 , 104.05],
       [  1.  , 104.05, 104.15, ..., 103.3 , 108.2 , 108.15]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X_poly,y,test_size=0.2,random_state=0)

In [ ]:
lin_reg2= LinearRegression()
lin_reg2.fit(X_poly,y)

LinearRegression()

In [ ]:
lin_reg2.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred= lin_reg2.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.999930771167945

# SVR

In [ ]:
X

array([[281.05, 283.  , 284.3 , 278.2 , 282.  , 281.6 ],
       [281.6 , 279.5 , 285.6 , 278.35, 280.65, 281.1 ],
       [281.1 , 281.25, 283.9 , 278.6 , 280.1 , 280.  ],
       ...,
       [103.2 , 103.75, 104.4 , 103.3 , 104.05, 103.9 ],
       [103.9 , 104.9 , 105.9 , 103.55, 104.3 , 104.05],
       [104.05, 104.15, 112.7 , 103.3 , 108.2 , 108.15]])

In [ ]:
y

array([281.78, 282.57, 280.92, ..., 103.9 , 104.39, 109.79])

In [ ]:
X.shape

(2456, 6)

In [ ]:
y.shape

(2456,)

In [ ]:
y=y.reshape(len(y),1)
y

array([[281.78],
       [282.57],
       [280.92],
       ...,
       [103.9 ],
       [104.39],
       [109.79]])

# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
X=sc_x.fit_transform(X)

sc_y=StandardScaler()
y=sc_y.fit_transform(y)

In [ ]:
X

array([[ 0.6448,  0.6616,  0.6335,  0.6564,  0.6564,  0.6517],
       [ 0.651 ,  0.6217,  0.6481,  0.6581,  0.641 ,  0.646 ],
       [ 0.6453,  0.6416,  0.629 ,  0.661 ,  0.6347,  0.6334],
       ...,
       [-1.3871, -1.3831, -1.3895, -1.3702, -1.3764, -1.3779],
       [-1.3791, -1.37  , -1.3726, -1.3673, -1.3736, -1.3762],
       [-1.3774, -1.3785, -1.2961, -1.3702, -1.329 , -1.3294]])

In [ ]:
y

array([[ 0.652 ],
       [ 0.661 ],
       [ 0.6422],
       ...,
       [-1.3793],
       [-1.3737],
       [-1.312 ]])

# Training SVR model on dataset

In [ ]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf')
regressor.fit(X,y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [ ]:
X

array([[ 0.6448,  0.6616,  0.6335,  0.6564,  0.6564,  0.6517],
       [ 0.651 ,  0.6217,  0.6481,  0.6581,  0.641 ,  0.646 ],
       [ 0.6453,  0.6416,  0.629 ,  0.661 ,  0.6347,  0.6334],
       ...,
       [-1.3871, -1.3831, -1.3895, -1.3702, -1.3764, -1.3779],
       [-1.3791, -1.37  , -1.3726, -1.3673, -1.3736, -1.3762],
       [-1.3774, -1.3785, -1.2961, -1.3702, -1.329 , -1.3294]])

In [ ]:
y

array([[ 0.652 ],
       [ 0.661 ],
       [ 0.6422],
       ...,
       [-1.3793],
       [-1.3737],
       [-1.312 ]])

In [ ]:
y_pred=regressor.predict(X)
y_pred

array([ 0.6541,  0.6469,  0.6417, ..., -1.4396, -1.4307, -1.3984])

In [ ]:
y_test=sc_y.inverse_transform(y)
y_test

array([[281.78],
       [282.57],
       [280.92],
       ...,
       [103.9 ],
       [104.39],
       [109.79]])

In [ ]:
from sklearn.metrics import r2_score
r2_score(y,y_pred)

0.99839553546944

# Decision Tree Regressor

In [ ]:
X= d.iloc[ : , 0:6].values
X

array([[281.05, 283.  , 284.3 , 278.2 , 282.  , 281.6 ],
       [281.6 , 279.5 , 285.6 , 278.35, 280.65, 281.1 ],
       [281.1 , 281.25, 283.9 , 278.6 , 280.1 , 280.  ],
       ...,
       [103.2 , 103.75, 104.4 , 103.3 , 104.05, 103.9 ],
       [103.9 , 104.9 , 105.9 , 103.55, 104.3 , 104.05],
       [104.05, 104.15, 112.7 , 103.3 , 108.2 , 108.15]])

In [ ]:
y= d.iloc[ : , 6].values
y

array([281.78, 282.57, 280.92, ..., 103.9 , 104.39, 109.79])

#Training Decision Tree Model

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor= DecisionTreeRegressor(random_state=0)
regressor.fit(X,y)

DecisionTreeRegressor(random_state=0)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y,regressor.predict(X))

1.0

#Random Forest Regressor

In [ ]:
X

array([[281.05, 283.  , 284.3 , 278.2 , 282.  , 281.6 ],
       [281.6 , 279.5 , 285.6 , 278.35, 280.65, 281.1 ],
       [281.1 , 281.25, 283.9 , 278.6 , 280.1 , 280.  ],
       ...,
       [103.2 , 103.75, 104.4 , 103.3 , 104.05, 103.9 ],
       [103.9 , 104.9 , 105.9 , 103.55, 104.3 , 104.05],
       [104.05, 104.15, 112.7 , 103.3 , 108.2 , 108.15]])

In [ ]:
y

array([281.78, 282.57, 280.92, ..., 103.9 , 104.39, 109.79])

##Training Random Forest model

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(n_estimators=10, random_state=0)
regressor.fit(X,y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y,regressor.predict(X))

0.999972343093303

In [4]:
my_dict= {
    "Linear Regression":0.9995126613336639,
    "Multiple Regression": 0.999930771167945,
    "Polynomial Regression": 0.999930771167945,
    "SVR": 0.99839553546944,
    "Decision Tree": 1.0,
    "Random Forest": 0.999972343093303
}

In [6]:
Series= pd.Series(my_dict)
Series

Linear Regression        0.999513
Multiple Regression      0.999931
Polynomial Regression    0.999931
SVR                      0.998396
Decision Tree            1.000000
Random Forest            0.999972
dtype: float64